services:
  mariadb:
    container_name: mariadb			
    networks:
      - inception            			
    build: 
      context: srcs/mariadb 	
      dockerfile: Dockerfile	
    image: inception-mariadb:latest
    env_file: .env
    secrets:
      - db_root_password
      - db_user_password
    volumes:                       
      - mariadb:/var/lib/mysql
    restart: on-failure
    expose:                        
        - "3306" 
  nginx:
    container_name: nginx
    volumes:
      - wordpress:/var/www/wordpress
      - phpmyadmin:/var/www/phpmyadmin
    networks:
      - inception
    depends_on:        			 
      - wordpress
    build: 
      context: srcs/nginx
      dockerfile: Dockerfile
    image: inception-nginx:latest
    env_file: .env
    restart: on-failure
    ports:
    - "443:443" 		
  wordpress:
    container_name: wordpress
    env_file: .env
    secrets:
      - db_root_password
      - db_user_password
    volumes:
      - wordpress:/var/www/wordpress
    networks:
      - inception
    build: 
      context: srcs/wordpress
      dockerfile: Dockerfile
    image: inception-wordpress:latest
    depends_on:    					
      - mariadb
    restart: on-failure
    expose: 
    - "9000"
  phpmyadmin:
    container_name: phpmyadmin
    env_file: .env
    secrets:
      - db_user_password
    volumes:
      - phpmyadmin:/var/www/phpmyadmin
    networks:
      - inception
    build: 
      context: srcs/phpmyadmin
      dockerfile: Dockerfile
    image: inception-phpmyadmin:latest
    depends_on:    					
      - mariadb
    restart: on-failure
    expose: 
    - "9000"

volumes:
  wordpress:
    driver: local 
    driver_opts:
      type: 'none' 								
      o: 'bind'
      device: '/home/$USER/data/wordpress' 		
  phpmyadmin:
    driver: local 
    driver_opts:
      type: 'none' 								
      o: 'bind'
      device: '/home/$USER/data/phpmyadmin'
  mariadb:
    driver: local
    driver_opts:
      type: 'none' 
      o: 'bind'										 
      device: '/home/$USER/data/mariadb'
secrets:
  db_root_password:
    file: 	./secrets/db_root_password.txt			
  db_user_password:
    file: ./secrets/db_user_password.txt
networks:
  inception:
    driver: bridge		