#user  nobody;
worker_processes  1;

#error_log  logs/error.log;
#error_log  logs/error.log  notice;
#error_log  logs/error.log  info;

#pid        logs/nginx.pid;


events {
    worker_connections  1024;
}


http {
    include       mime.types;
    default_type  application/octet-stream;

    #log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
    #                  '$status $body_bytes_sent "$http_referer" '
    #                  '"$http_user_agent" "$http_x_forwarded_for"';

    #access_log  logs/access.log  main;

    sendfile        on;
    #tcp_nopush     on;

    #keepalive_timeout  0;
    keepalive_timeout  65;

    #gzip  on;

   server {
		#SSL/TLS Configuration
		listen 443 ssl;
		ssl_protocols TLSv1.2 TLSv1.3;
		ssl_certificate /etc/nginx/ssl/inception.crt;
		ssl_certificate_key /etc/nginx/ssl/inception.key;
		#root and index and server_name
		root /var/www/wordpress;
		server_name pde-petr.42.fr;
		index index.php index.html index.htm;
        location / {
		    try_files $uri $uri/ =404;
        }
        location ~ \.php$ {								# Pour toutes les requetes php
		    include snippets/fastcgi-php.conf;
		    fastcgi_pass wordpress:9000;
        }				# Comment renvoyer les requetes php sur le port 9000
	}

}
    
	